package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, STOP_JOB, JOB_SCHEDULE, 
	
	REQUEST, REPLY, RELEASE, RELEASE_CRITICAL_SECTION, QUIT, COMPUTED_POINTS,
	JOB_EXECUTION, ACK_JOB_EXECUTION, IDLE, ACK_IDLE,
	ASK_STATUS, TELL_STATUS, 
	JOB_RESULT, ASK_JOB_RESULT, ASK_JOB_FRACTALID_RESULT, JOB_FRACTALID_RESULT,
	
}
